# ─────────────────────────────────────────────────────────────────────────────
# EC2 1 — Backend Spring Boot + Frontend Angular
# Usuario Docker Hub: alexandraquispe
#
# ANTES DE LEVANTAR en EC2: reemplaza IP_PRIVADA_EC2_BD
# por la IP privada de tu instancia EC2 de base de datos
#
# Levantar:       docker compose -f docker-compose-app.yml up -d
# Bajar:          docker compose -f docker-compose-app.yml down
# Logs backend:   docker logs springboot-backend -f
# Logs frontend:  docker logs angular-frontend -f
# ─────────────────────────────────────────────────────────────────────────────

version: '3'

services:

  backend:
    image: alexandraquispe/springboot-sqlserver:1.0
    container_name: springboot-backend
    ports:
      - "8085:8085"
    environment:
      - PORT=8085
      - SERVER_URL=http://localhost:8085
      # ↓ Reemplaza por la IP PRIVADA de tu EC2 de base de datos
      # Ejemplo: jdbc:sqlserver://172.31.95.71:1433;databaseName=avsa_db;...
      - DATABASE_URL=jdbc:sqlserver://IP_PRIVADA_EC2_BD:1433;databaseName=avsa_db;encrypt=true;trustServerCertificate=true
      - DATABASE_USERNAME=sa
      - DATABASE_PASSWORD=Admin12345!!
      - DATABASE_DRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      # ↓ Reemplaza por la IP PÚBLICA de esta instancia EC2 (backend+frontend)
      # Ejemplo: - CORS_ALLOWED_ORIGINS=http://54.234.136.243
      - CORS_ALLOWED_ORIGINS=http://IP_PUBLICA_EC2_1
    networks:
      - my-network
    restart: unless-stopped

  frontend:
    image: alexandraquispe/frontend-angular:latest
    container_name: angular-frontend
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  my-network:
    external: true
