server:
  port: ${PORT:8085}
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=CustomerDB;encrypt=false
    username: sa
    password: Gala123$
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html