# docker-compose -f docker-compose-db.yml up -d
# docker-compose -f docker-compose-db.yml down
services:
  backend:
    image: anthonygala/springboot-sqlserver:1.0
    container_name: springboot-sqlserver
    restart: unless-stopped
    ports:
      - "8085:8085"
    environment:
      - PORT=8085
      - SERVER_URL=http://localhost:8085
      - DATABASE_URL=jdbc:sqlserver://sql-server:1433;databaseName=CustomerDB;encrypt=false;trustServerCertificate=true
      - DATABASE_USERNAME=sa
      - DATABASE_PASSWORD=Admin12345!
      - DATABASE_DRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - my-network

  sqlserver:
    image: anthonygala/sql-server:2022   # cambiar por tu usuario de dockerhub
    container_name: sql-server
    restart: unless-stopped
    environment:
      SA_PASSWORD: "Admin12345!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "grep -q 'SQL Server is now ready for client connections' /var/opt/mssql/log/errorlog || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 40s
    networks:
      - my-network

# CREAR UNA RED EN ESTE COMPOSE PARA QUE SEA COMPARTIDA
networks:
  my-network:
    name: my-network   # red compartida, visible desde ambos compose
    driver: bridge

volumes:
  sqlserver_data:
